### PR TITLE
Update pinpoint.sh

### PR DESCRIPTION
**Pull request by ofirgalcon**
fix wrong macOS version check

### CODE REVIEW

**Comment by jelockwood** [comment]
@ofirgalcon 
An admittedly much delayed response. I can see this commit changes the way the macOS version is checked. Can you explain the purpose for this change because as far as I could see the original method whilst different does work and is the more common approach and easier to read.

I have another commit from someone else and I would like to get yours resolved first so cheekily if you can answer soonish this will help with then moving on to the second one. 🥲

**Comment by ofirgalcon** [comment]
I can't remember why I changed it, I just remember that I had to

**Comment by precursorca** [comment]
I believe the issue is with the &&. 
i.e. it has to be 14 AND 4 or greater. That means means a major of 15 with a minor of less than 4 fails.
I solved it another way in my own fork but I do like Ofirgalcon's code much better!

**Comment by jelockwood** [comment]
@ofirgalcon @precursorca 
Ugh! I had a look at this and first built a smaller test script just to test my original logic which is indeed non-functional. At first it looked like a simple fix would do the job but it got uglier and uglier.

I am therefore going to accept this push. Thanks @ofirgalcon  😄

**Pull request merged**
